baseURL = "https://lokal.ninja/baden-wuerttemberg"
languageCode = "de-DE"
title = "Baden-Württemberg"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  site = "Lokal Ninja"
  org = "lokal-ninja"
  repo = "baden-wuerttemberg"
